version: "3.3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db-keen-eye/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root       
    ports:
      - 27018:27018
      - 27017:27017